# Generated by Django 3.2.12 on 2022-09-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('success', models.CharField(default='Success!!', max_length=20)),
            ],
        ),
    ]
