# Generated by Django 3.2.12 on 2022-09-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArrayTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('success', models.CharField(default='Success!!', max_length=20)),
            ],
        ),
    ]
