# Generated by Django 3.2.12 on 2022-09-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangotest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrayTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.JSONField(default='{}')),
            ],
        ),
    ]
