# Generated by Django 3.2.12 on 2022-09-22 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordchain',
            old_name='user_id',
            new_name='user',
        ),
    ]
