# Generated by Django 3.2.12 on 2022-09-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_user_id_wordchain_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exp_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
