# Generated by Django 3.2.12 on 2022-09-27 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_mbti'),
        ('accounts', '0005_user_name'),
    ]

    operations = [
    ]
