# Generated by Django 3.2.12 on 2022-09-30 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_0002_mbti_0005_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.DeleteModel(
            name='WordChain',
        ),
    ]
