# Generated by Django 3.2.12 on 2022-10-06 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20220916_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_item',
            name='item',
        ),
        migrations.RemoveField(
            model_name='user_item',
            name='user',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='User_Item',
        ),
    ]
