# Generated by Django 3.2.12 on 2022-09-12 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.TextField()),
                ('feeds', models.JSONField(default=list)),
                ('characteristics', models.JSONField(default=list)),
                ('commands', models.JSONField(default=list)),
                ('default_color', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('exp', models.IntegerField()),
                ('is_located', models.BooleanField()),
                ('color_id', models.IntegerField()),
                ('talking_cnt', models.IntegerField()),
                ('playing_cnt', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('last_eating_time', models.DateTimeField()),
                ('level', models.IntegerField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.animal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
