# Generated by Django 3.2.12 on 2022-09-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_animal',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_animal',
            name='is_located',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_animal',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_animal',
            name='playing_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_animal',
            name='talking_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
