# Generated by Django 3.2.12 on 2022-09-13 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_animal',
            name='color_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user_animal',
            name='last_eating_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 12, 4, 53, 954510)),
        ),
    ]
