# Generated by Django 3.2.12 on 2022-09-14 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_auto_20220914_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_animal',
            name='last_eating_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 4, 19, 43, 77871)),
        ),
    ]
