# Generated by Django 3.2.12 on 2022-09-14 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_alter_user_animal_last_eating_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_animal',
            name='color_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_animal',
            name='last_eating_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 4, 20, 41, 387726)),
        ),
    ]
