# Generated by Django 3.2.12 on 2022-09-14 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_auto_20220914_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='default_color',
        ),
        migrations.AlterField(
            model_name='user_animal',
            name='last_eating_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 6, 30, 0, 632659)),
        ),
    ]
