# Generated by Django 3.2.12 on 2022-09-14 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_auto_20220914_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_animal',
            name='color_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_animal',
            name='last_eating_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 6, 31, 50, 242920)),
        ),
    ]
