# Generated by Django 3.2.12 on 2022-09-16 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_auto_20220916_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='characteristics',
            new_name='features',
        ),
    ]
