# Generated by Django 3.2.12 on 2022-09-29 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0008_auto_20220927_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_animal',
            name='color_id',
        ),
    ]
