# Generated by Django 3.2.12 on 2022-10-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0009_remove_user_animal_color_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_animal',
            name='name',
            field=models.CharField(max_length=5),
        ),
    ]
